const container = document.querySelector('main .container');
const image = document.getElementById("music_image");
const audio = document.getElementById("audio")
const music_title = document.querySelector("#music_details .title");
const music_singer = document.querySelector("#music_details .singer");
const prev = document.querySelector("#controls #prev");
const play = document.querySelector("#controls #play");
const next = document.querySelector("#controls #next");
const duration = document.getElementById("duration");
const current_time = document.getElementById("current-time");
const progress_bar = document.getElementById("progress-bar");
const volume_icon = document.getElementById("volume");
const volume_bar = document.getElementById("volume-bar");
const ul = document.querySelector("ul");
const newMusic = document.getElementById('file');
const newImg = document.getElementById('img');
const singer = document.getElementById('singer');
const title = document.getElementById('title');